[general]
live_config_reload = true

[window]
opacity = 0.975
option_as_alt = "Both"

[font]
normal = { family = "Inconsolata", style = "Regular" }
bold = { family = "Inconsolata", style = "Bold" }
italic = { family = "Inconsolata", style = "Italic" }
bold_italic = { family = "Inconsolata", style = "Bold Italic" }
size = 16.0
